version: 2
updates:
  - package-ecosystem: npm
    directory: /yt2future-f2-v2
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /yt2future-be-v2
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
